const express = require('express')

const notImplemented = require('../middlewares/notImplemented')

module.exports = express.Router()
  .get('/', notImplemented)
  .post('/', notImplemented)
  .put('/', notImplemented)
  .patch('/', notImplemented)
  .delete('/', notImplemented)
  .get('/:officeId', notImplemented)
  .post('/:officeId', notImplemented)
  .put('/:officeId', notImplemented)
  .patch('/:officeId', notImplemented)
  .delete('/:officeId', notImplemented)
  .get('/:officeId/user', notImplemented)
  .post('/:officeId/user', notImplemented)
  .put('/:officeId/user', notImplemented)
  .patch('/:officeId/user', notImplemented)
  .delete('/:officeId/user', notImplemented)
  .get('/:officeId/user/:userId', notImplemented)
  .post('/:officeId/user/:userId', notImplemented)
  .put('/:officeId/user/:userId', notImplemented)
  .patch('/:officeId/user/:userId', notImplemented)
  .delete('/:officeId/user/:userId', notImplemented)
